### ISSUE TITLE
Wrong host name

### ISSUE THREAD

**Issue by mmalchuk** [niktheworker/testwaves#1]
https://github.com/niktheworker/testwaves/blob/4ca94ccd7d2244b94066c6d983dda4ade55c54e5/testwaves.yml#L6

Should use **utility_all[0]** instead of **utility[0]**

**Comment by niktheworker** [comment]
fixed https://github.com/niktheworker/testwaves/commit/6c91ccc7e3dbb0e991031acf505dbf215c66a66c
